image:
  file: Dockerfile

tasks:
  - name: Clone repos
    command: ./clone-repos.sh

vscode:
  extensions:
    - sourcegraph.cody-ai
    - quarto.quarto
    - REditorSupport.r
    - bierner.markdown-preview-github-styles
