image:
  file: gitpod.Dockerfile

tasks:
  - name: Clone repos and install tinytex
    command: ./clone-repos.sh && \
      quarto install tinytex

vscode:
  extensions:
    - sourcegraph.cody-ai
    - quarto.quarto
    - REditorSupport.r
    - bierner.markdown-preview-github-styles
